version: '3'

services:

    web:
        image: 'dontdrinkandroot/php:20-04-8-0-dev'
        ports:
            - "8000:80"
        depends_on:
            - postgres
        volumes:
            - ./:/var/www/
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

    postgres:
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
